"""add source metadata and media dimensions to videos

Revision ID: 06633c265463
Revises: 4fce4c2898e7
Create Date: 2026-08-14 22:00:30.144373+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06633c265463"
down_revision: str | Sequence[str] | None = "4fce4c2898e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("width", sa.Integer(), nullable=True))
    op.add_column("videos", sa.Column("height", sa.Integer(), nullable=True))
    op.add_column("videos", sa.Column("source_id", sa.Text(), nullable=True))
    op.add_column("videos", sa.Column("source_title", sa.Text(), nullable=True))
    op.add_column("videos", sa.Column("source_description", sa.Text(), nullable=True))
    op.add_column("videos", sa.Column("source_uploader", sa.Text(), nullable=True))
    op.add_column("videos", sa.Column("source_uploader_id", sa.Text(), nullable=True))
    op.add_column(
        "videos",
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "videos", sa.Column("source_view_count", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "videos",
        sa.Column("source_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "source_raw")
    op.drop_column("videos", "source_view_count")
    op.drop_column("videos", "source_published_at")
    op.drop_column("videos", "source_uploader_id")
    op.drop_column("videos", "source_uploader")
    op.drop_column("videos", "source_description")
    op.drop_column("videos", "source_title")
    op.drop_column("videos", "source_id")
    op.drop_column("videos", "height")
    op.drop_column("videos", "width")
    # ### end Alembic commands ###
