"""drop download_jobs table

Revision ID: 078c55faffba
Revises: 06633c265463
Create Date: 2026-08-15 16:03:42.258211+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "078c55faffba"
down_revision: str | Sequence[str] | None = "06633c265463"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("download_jobs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_jobs",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("video_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("download_jobs_pkey")),
        sa.UniqueConstraint(
            "video_id",
            name=op.f("download_jobs_video_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
